

package:
  name: pyelmmme
  version: "0.1.5"

source:
  url: https://github.com/kjhall01/PyELM-MME/archive/refs/tags/v0.1.5.tar.gz

build:
  number: 0
  string: pyelmmme
  entry_points:
  - pyelm1d = pyelmmme.key:pyelm1d_main
  - pyelm2d = pyelmmme.key:pyelm2d_main


requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cartopy
    - numpy
    - xarray
    - pandas
    - pathlib
    - matplotlib
    - scikit-learn
    - scipy
    - pytables
    - fasteners

test:
  imports:
    - pyelmmme

about:
  home: https://github.com/kjhall01/PyELM-MME
  license: MIT
  summary: 'Using ELM for Climate Forecasting / Multi-Model Ensemble analysis'
  description: 'wrapper and data wrangler for MME methodologies including hpelm (Extreme Learning Machine)'
  dev_url: https://github.com/kjhall01/PyELM-MME
  doc_url: https://doi.org/10.5281/zenodo.4515069
